echo "Never gonna give you up"
echo "Never gonna let you down"
echo "Never gonna run around and desert you"
echo "Never gonna make you cry"
echo "Never gonna say goodbye"
echo "Never gonna tell a lie and hurt you"
echo "Never gonna stop"
echo "Never gonna give you up"
echo "Never gonna let you down"
echo "Never gonna run around and desert you"
echo "Never gonna make you cry"
echo "Never gonna say goodbye"
echo "Never gonna tell a lie and hurt you"
echo "//////////Dont run random shit from the internet kids//////////"
